security:
  basic:
    enabled: true
  user:
    name: username
    password: password123
server:
  port: 8761
eureka: 
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://username:password123@localhost:8761/eureka/