spring:
  application:
    name: simple-consumer-user
server:
  port: 8182
user:
  userServicePath: http://localhost:8182/simple/
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://username:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}